### ISSUE TITLE
Job Part -> final size value is not matching

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#11]
Hi,

I just recognize that the value of final size on the pace system is not matching with the value from api.

For example,

The final size on my pace system is 22″ x 28″. The value from API is 65.0. 

Could you advise me on this please?

Thanks,
Ryan

**Comment by robgridley** [comment]
Which version of Pace are you using? In v27 there is no finalSize field on the JobPart object. There are finalSizeW and finalSizeH fields which are floats (in inches).

```php
$jobPart = $pace->model('JobPart')->read('75440:01');

var_dump($jobPart->finalSizeW);
var_dump($jobPart->finalSizeH);
```
Result:
```
float(4)
float(9.375)
```

**Comment by rkang30** [comment]
Thanks @robgridley 

The field on the system is referencing to finalSizeH. But I guess I will have to use both finalSizeW and finalSizeH. 

Ryan

**Comment by rkang30** [comment]
the final size on the pace system is 23 5/8″ x 65″. the api values are finalSizeW: 23.625, finalSizeH: 65.0. 

Is there any php function that reverts 0.625 to 5/8?

**Comment by robgridley** [comment]
Maybe check out this library: https://github.com/phospr/fraction

**Comment by rkang30** [comment]
Awesome! Thanks for your great Help!

**Comment by robgridley** [comment]
No problem. I wish Pace would pass a special type for measurements (instead of decimal) in the SOAP API. If they did, I could turn the value into an object, like the really handy [PHP Units of Measure](https://github.com/PhpUnitsOfMeasure/php-units-of-measure). I try to work with metric as much as possible, but everything has to be converted to inches and pounds because the print industry in Canada is tied to the American way of doing things.
