### ISSUE TITLE
how to catch the soap error !!

### ISSUE THREAD

**Issue by saung87** [robgridley/pace-api#42]
Hi,

 i want to create a login function to pace using the pace api with laravel, so how can i catch the SOAP error if the username and password is not correct to connect to the pace server rather than getting this error "**SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://192.168.1.127/rpc/services/FindObjects?wsdl' : failed to load external entity "http://192.168.1.127/rpc/services/FindObjects?wsdl**"..

Thank you..

**Comment by saung87** [comment]
@robgridley  hello rob gridley, can you please point me out how to do the login control function for the pace?

**Comment by JoeKuhns** [comment]
Check out this thread on SO.  I think it has what you want to do...

[https://stackoverflow.com/questions/6952814/php-soap-error-catching/16394213](https://stackoverflow.com/questions/6952814/php-soap-error-catching/16394213)

Basically if you are running php7+. you can do this...

`try{
    soap connection...
}catch(Throwable $e){
    echo 'sorry... our service is down';
}`

**Comment by robgridley** [comment]
@JoeKuhns is correct. You would need to catch the SoapFault exception and check the message or code to determine if is an authentication failure.

However, I don't think what you are trying to do is a good idea. When you enable API access it throws all user permissions out the window. When a user has API access enabled, and they access Pace via the API, can they access any object in the system, regardless of their group memberships and permissions.

You should have one user defined in Pace which your application uses to access the API. You should handle all authentication and authorization in your application, since the Pace API does not enforce any permissions.

I have implemented single sign-on with Pace, but I implemented it by comparing the credentials against the SystemUser object. The password hashes are pretty basic. They're Base64-encoded MD5 sums. Here is a quick code example:

```php
// $username and $password are the user's inputs

$systemUser = $pace->model('SystemUser')
    ->filter('@userName', $username)
    ->filter('@locked', false)
    ->first();

if (is_null($systemUser)) {
    // auth failed; user does not exist or is locked
}

if ($systemUser->password === base64_encode(md5($password, true))) {
    // auth succeeded
} else {
    // auth failed; password does not match
}
```

**Comment by saung87** [comment]
@JoeKuhns and @robgridley  thank you both for the help, i will look into it.
